[package]
name = "rarduino"
version = "0.1.0"
edition = "2021"

[dependencies]
bindgen = "0.70.1"
cc = "1.1.31"
envmnt = "0.10.4"
glob = "0.3.1"
serde = { version = "1.0.213", features = ["derive"] }
thiserror = "1.0.65"
